<?php

namespace App\Services\Ai;

use Illuminate\Support\Facades\Http;
use RuntimeException;

class GeminiService
{
    public function generateStructuredData(string $prompt, array $fields): array
    {
        $apiKey = config('ai.gemini.api_key');
        $model = config('ai.gemini.model');

        /* 
        curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-preview:generateContent" \
  -H "x-goog-api-key: $GEMINI_API_KEY" \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '{
    "contents": [{
      "parts": [{"text": "Find the race condition in this multi-threaded C++ snippet: [code here]"}]
    }]
  }'
        */
        // Use v1beta (Beta) https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-preview:generateContent
        $url = "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key={$apiKey}";

        $response = Http::timeout(60)->post($url, [
            'contents' => [
                [
                    'parts' => [
                        [
                            // Strict prompting is required when native JSON mode is unavailable
                            'text' => "Return ONLY a JSON object. Do not include markdown code blocks. Do not include any text before or after the JSON. Expected keys: " . implode(', ', $fields) . ". \n\nContext: " . $prompt
                        ]
                    ]
                ]
            ],
            'generationConfig' => [
                'temperature' => (float) config('ai.gemini.temperature'),
                'maxOutputTokens' => (int) config('ai.gemini.max_tokens'),
                // 'response_mime_type' removed because it causes 400 errors on v1
            ],
        ]);

        if (!$response->successful()) {
            throw new RuntimeException('AI generation failed: ' . $response->body());
        }

        $content = $response->json('candidates.0.content.parts.0.text');

        if (!$content) {
            throw new RuntimeException('No content generated by Gemini AI');
        }

        return $this->extractJson($content, $fields);
    }

    private function extractJson(string $content, array $fields): array
    {
        // 1. Clean up any accidental markdown backticks or hidden whitespace
        $cleanContent = trim($content);

        // Remove ```json blocks if the AI ignored our "no markdown" instruction
        if (preg_match('/^```json\s+(.*)\s+```$/s', $cleanContent, $matches)) {
            $cleanContent = $matches[1];
        } elseif (preg_match('/^```\s+(.*)\s+```$/s', $cleanContent, $matches)) {
            $cleanContent = $matches[1];
        }

        $json = json_decode(trim($cleanContent), true);

        if (json_last_error() !== JSON_ERROR_NONE) {
            throw new RuntimeException('Invalid AI JSON response. Raw content: ' . $content);
        }

        // Whitelist fields to ensure we only return what was requested
        return array_intersect_key($json, array_flip($fields));
    }
}
